### PR TITLE
Analytics branch PR

### PR DESCRIPTION
**Pull request by Metasynic**
Algorithm now takes the list of data points from the CSV and maps them onto each edge from the JSON, but takes about 7 minutes to do so. It'll be optimized momentarily but this should be good for now.

### CODE REVIEW

**Comment by Metasynic** [comment]
I'll leave this alone now, all we need to do is adjust parameters depending on the route output.

**Comment by mukul-rathi** [comment]
Good job! Let's hold off on merging this until Travis CI is set up for the repo this weekend.

**Comment by mukul-rathi** [comment]
Hey, just a minor adjustment to your commit message style - use the imperative tense i.e this commit will _____.

**Comment by mukul-rathi** [comment]
I've resolved the gitignore merge conflict, let's just wait for Travis to run otherwise looks good to me!

**Pull request merged**
